import './App.css';
import {CLABSChat} from './ChatComponent';

const coreExamples = [["text","Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur."],["carousel","[\"https://bouqs.com/blog/wp-content/uploads/2021/09/snapdragon-20809_1280.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2019/05/20_summer-cosmos.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2019/05/summer-dahlia.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2023/06/zinnia-gbcbfedd94_1280.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2021/09/chrysanthemum-5668882_1280.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2021/09/celosia-7299458_1280.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2021/05/sunflower-fields.jpg\",\"https://bouqs.com/blog/wp-content/uploads/2021/09/strawflower-362280_1280.jpg\"]","","Flower images from bouqs.com"],["text","Abraham Lincoln was an American lawyer, politician, and statesman who served as the 16th [president of the United States](https://en.wikipedia.org/wiki/President_of_the_United_States) from 1861 until his [assassination](https://en.wikipedia.org/wiki/Assassination_of_Abraham_Lincoln) in 1865. Lincoln led the United States through the [American Civil War](https://en.wikipedia.org/wiki/American_Civil_War), defending the nation as a constitutional [union](https://en.wikipedia.org/wiki/Union_(American_Civil_War)\n [Many more links are available in this article](https://en.wikipedia.org/wiki/Log_cabin,https://en.wikipedia.org/wiki/Kentucky,https://en.wikipedia.org/wiki/American_frontier,https://en.wikipedia.org/wiki/Indiana). ","annotated-text","Abraham Lincoln article on Wikipedia"],["code","```<clabs-chat \n\tuser-name=\"Owen\" \n\tagent-name=\"Watson\"\n\tconversation={conversationJSON}\n\tstream-responses={streamEnabled}\n\tloading={loading}\n\tdefault-viewing-mode=\"docked\"\n\ton:on-user-message-update-request={handleUpdatedMessage}\n\ton:on-user-regeneration-request={handleRegeneration}\n\ton:on-user-text-input={handleNewMessage}\n\ton:on-message-element-selected={handleElementClicked}\n\ton:on-user-feedback-request={handleUserFeedback}\n\ton:on-message-element-tag-selected={handleTagClicked}>\n</clabs-chat>```","","Prime function in python"],["link-list","[IBM Cloud Home](https://www.ibm.com/cloud),[Cloud Solutions](https://www.ibm.com/cloud/solutions),[Cloud products](https://www.ibm.com/cloud/products),[Cloud Docs](https://cloud.ibm.com/docs)","","List of links in IBM Cloud"],["formula","\\(1 +  \frac{q^2}{(1-q)}+\frac{q^6}{(1-q)(1-q^2)}+\\cdots =    \\prod_{j=0}^{\\infty}\frac{1}{(1-q^{5j+2})(1-q^{5j+3})},     \\quad\\quad \text{for $|q| < 1$}.\\)","","Rogers-Ramanujan Identity equation in tex"],["formula","\\( S = -\frac{1}{2}\\int d^2\\sigma \\sqrt{-h} h^{ab}\\partial_a X^\\mu \\partial_b X^\\mu \\\\ \frac{1}{4 \\pi \\alpha'} \\int d^2\\sigma \\sqrt{-h} \\left( h^{ab} \\partial_a X^\\mu \\partial_b X_\\mu + \\alpha' R \\Phi(X) \right  \\\\ [\\alpha_m^\\mu, \\alpha_n^\nu] = m \\delta_{m+n,0} \\eta^{\\mu \nu}  \\)","","String Theory Action"],["table","Name,Age,Occupation,Location,State\nJerry,35,Comedian,Upper east side,NY\nGeorge,35,Unemployed,Queens,NY\nElaine,32,Publisher,Midtown,NY\nKramer,36,Unknown,Upper east side,NY","","Seinfeld characters"],["list","1. Google.com (United States)\n2. YouTube.com (US)\n3. Facebook.com (US)\n4. Baidu.com (China)\n5. Wikipedia.org (US)","","Top sites in the United States"],["text","[International Business Machines Corporation](https://en.wikipedia.org/wiki/IBM) (using the trademark IBM), nicknamed [Big Blue](https://en.wikipedia.org/wiki/Big_Blue), is an American [multinational](https://en.wikipedia.org/wiki/Multinational_corporation) [technology company](https://en.wikipedia.org/wiki/Technology_company) headquartered in [Armonk, New York](https://en.wikipedia.org/wiki/Armonk,_New_York) and present in over 175 countries. IBM is the largest industrial [research organization](https://en.wikipedia.org/wiki/Research_institute) in the world, with 19 research facilities across a dozen countries, having held the record for most annual [U.S.](https://en.wikipedia.org/wiki/United_States) [patents](https://en.wikipedia.org/wiki/Patent) generated by a business for 29 consecutive years from 1993 to 2021","highlight-text","IBM article from wikipedia.com"],["molecule","```CC(C)(O1)C[C@@H](O)[C@@]1(O2)[C@@H](C)[C@@H]3CC=C4[C@]3(C2)C(=O)C[C@H]5[C@H]4CC[C@@H](C6)[C@]5(C)Cc(n7)c6nc(C[C@@]89(C))c7C[C@@H]8CC[C@@H]%10[C@@H]9C[C@@H](O)[C@@]%11(C)C%10=C[C@H](O%12)[C@]%11(O)[C@H](C)[C@]%12(O%13)[C@H](O)C[C@@]%13(C)CO```","","Smiles representation of Cephalostatin-1 from PubChem"],["molecule","```C1=NC(=C2C(=N1)N(C=N2)C3C(C(C(O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O)N.C1=NC(=C2C(=N1)N(C=N2)C3C(C(C(O3)COP(=O)(O)OP(=O)(O)OP(=O)(O)O)O)O)N```","","Smiles representation of ATP (Adenosine Triphosphate) from PubChem"],["file-upload","Test_file.pdf"],["card","https://dhjhkxawhe8q4.cloudfront.net/yup-wp/wp-content/uploads/2022/11/04134700/31_426_WMAA_Early-Sunday-Morning.jpg","img","Edward Hopper, Early Sunday Morning, 1930. Oil on canvas"],["card","https://www.wikipedia.org/wiki/Apollo_11","url","Apollo 11 article on wikipedia.com"],["card","https://upload.wikimedia.org/wikipedia/commons/transcoded/d/da/Paris_lockdown_-_Vimeo.webm/Paris_lockdown_-_Vimeo.webm.1080p.vp9.webm","video","Paris lockdown video from Wikipedia Commons"],["card","https://github.com/vega/vega-datasets/blob/main/data/co2-concentration.csv","file","C02 concentration spreadsheet from Github"],["card","https://upload.wikimedia.org/wikipedia/commons/f/f5/Giovanni_Giuseppe_Cambini_-_Quintet_No._1_in_Bb_major%2C_movement_2.ogg","audio","Audio file from Wikipedia commons"],["error","SEGMENTATION ERROR: Failed to render the content provided. (example)"],["loading",""],["html-text","<h2>This is using a h2 tag</h2>"],["tags","[\"Simone de Beauvoir\",\"René Descartes\",\"Jean-Paul Sartre\",\"Voltaire\",\"Michel Foucault\",\"Albert Camus\"]","","List of famous french philosophers"],["chart","{\"$schema\":\"https://vega.github.io/schema/vega-lite/v5.json\",\"title\":\"US Unemployment by county\",\"data\":{\"url\":\"https://vega.github.io/editor/data/us-10m.json\",\"format\":{\"type\":\"topojson\",\"feature\":\"counties\"}},\"transform\":[{\"lookup\":\"id\",\"from\":{\"data\":{\"url\":\"https://vega.github.io/editor/data/unemployment.tsv\"},\"key\":\"id\",\"fields\":[\"rate\"]}}],\"projection\":{\"type\":\"albersUsa\"},\"mark\":\"geoshape\",\"encoding\":{\"color\":{\"field\":\"rate\",\"type\":\"quantitative\"}}}","","Map example from vega-lite"],["chart","{\"$schema\":\"https://vega.github.io/schema/vega-lite/v5.json\",\"description\":\"A scatterplot showing body mass and flipper lengths of penguins.\",\"data\":{\"url\":\"https://vega.github.io/vega-lite/examples/data/penguins.json\"},\"mark\":\"point\",\"encoding\":{\"x\":{\"field\":\"Flipper Length (mm)\",\"type\":\"quantitative\",\"scale\":{\"zero\":false}},\"y\":{\"field\":\"Body Mass (g)\",\"type\":\"quantitative\",\"scale\":{\"zero\":false}},\"color\":{\"field\":\"Species\",\"type\":\"nominal\"}}}","","Scatter plot example from vega-lite"],["chart","{\"$schema\":\"https://vega.github.io/schema/vega-lite/v5.json\",\"width\":300,\"height\":200,\"data\":{\"url\":\"https://vega.github.io/vega-lite/data/unemployment-across-industries.json\"},\"mark\":\"area\",\"encoding\":{\"x\":{\"timeUnit\":\"yearmonth\",\"field\":\"date\",\"axis\":{\"domain\":false,\"format\":\"%Y\",\"tickSize\":0}},\"y\":{\"aggregate\":\"sum\",\"field\":\"count\",\"axis\":null,\"stack\":\"center\"},\"color\":{\"field\":\"series\",\"scale\":{\"scheme\":\"category20b\"}}}}","","Stream graph example from vega-lite"]]
const conversationProtocol =  [
    {
      origin: 'user',
      hasError: false,
      userSubmitted:true,
      time: '16:51',
      index: 0,
      elements: [
        {
          type: 'text',
          content:
            'Show me examples for the following components in this chat: ' +
            coreExamples.map((item) => item[0]).join(', '),
        },
      ],
    },
    {
      origin: 'bot',
      hasError: false,
      time: '16:55',
      index: 1,
      elements: coreExamples.reduce((acc, item, index) => {
        acc.push({
          type: 'html-text',
          content:
            '<b>' +
            (index + 1) +
            '.</b> Here is a <b>&lt;clabs-chat-' +
            item[0] +
            '&gt;</b> element' +
            (item[2] ? ' of type <i><b>' + item[2] + '</b></i>' : '') +
            ':' +
            (item[3]
              ? '<br/><span style="font-size:12px;font-style:italic;">' +
                item[3] +
                '</span>'
              : ''),
        });
        acc.push({ type: item[2] ? item[2] : item[0], content: item[1] });
        //acc.push({"type":"html-text","content":item[3]?'\n<p style="font-size:12px;font-style:italic;">'+item[3]+'</p>':''})
        return acc;
      }, []),
    },
  ]


function App() {
  return (
    <div className="App">
      <div className="Container">
        <CLABSChat conversation={conversationProtocol}> 

        </CLABSChat>
      </div>
    </div>
  );
}

export default App;
